const tailwindConfig = {
  theme: {
    extend: {
      fontFamily: {
        mono: [
          'var(--font-mono)',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
        sans: [
          'var(--font-sans)',
          'var(--font-sans-sc)',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'hsl(var(--heroui-foreground))',
            '--tw-prose-bold': 'hsl(var(--heroui-foreground-700))',
            '--tw-prose-bullets': 'hsl(var(--heroui-foreground))',
            '--tw-prose-captions': 'hsl(var(--heroui-foreground))',
            '--tw-prose-code': 'hsl(var(--heroui-foreground))',
            '--tw-prose-counters': 'hsl(var(--heroui-foreground))',
            '--tw-prose-headings': 'hsl(var(--heroui-foreground-700))',
            '--tw-prose-hr': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-body': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-bold': 'hsl(var(--heroui-foreground-700))',
            '--tw-prose-invert-bullets': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-captions': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-code': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-counters': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-headings': 'hsl(var(--heroui-foreground-700))',
            '--tw-prose-invert-hr': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-kbd': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-kdb-shadows': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-lead': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-links': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-pre-bg': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-pre-code': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-quote-borders': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-quotes': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-td-borders': 'hsl(var(--heroui-foreground))',
            '--tw-prose-invert-th-borders': 'hsl(var(--heroui-foreground))',
            '--tw-prose-kbd': 'hsl(var(--heroui-foreground))',
            '--tw-prose-kdb-shadows': 'hsl(var(--heroui-foreground))',
            '--tw-prose-lead': 'hsl(var(--heroui-foreground))',
            '--tw-prose-links': 'hsl(var(--heroui-foreground))',
            '--tw-prose-pre-bg': 'hsl(var(--heroui-foreground))',
            '--tw-prose-pre-code': 'hsl(var(--heroui-foreground))',
            '--tw-prose-quote-borders': 'hsl(var(--heroui-foreground))',
            '--tw-prose-quotes': 'hsl(var(--heroui-foreground))',
            '--tw-prose-td-borders': 'hsl(var(--heroui-foreground))',
            '--tw-prose-th-borders': 'hsl(var(--heroui-foreground))',
            blockquote: {
              fontStyle: 'normal',
              fontWeight: 'inherit',
            },
            'blockquote p:first-of-type::before': {
              content: '',
            },
            'blockquote p:last-of-type::after': {
              content: '',
            },
            code: {
              fontWeight: 600,
              color: 'hsl(var(--heroui-primary-600));',
            },
            pre: {
              fontWeight: 500,
              background: 'inherit',
            },
          },
        },
      },
    },
  },
};

export default tailwindConfig;
